### Numpy basics

In [1]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [35]:
m = np.arange(12).reshape((3,4))

r_means = [np.mean(m[i, :]) for i in range(len(m[:]))] 
c_means = [np.mean(m[:, i]) for i in range(len(m[0,:]))]
print("means (rows, cols):", (r_means, c_means), "\n", "overall mean:", np.mean(m))

means (rows, cols): ([np.float64(1.5), np.float64(5.5), np.float64(9.5)], [np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0)]) 
 overall mean: 5.5


2\. Find the outer product of the following two vecotrs

The outer product between two vectors is defined as following:

   [[a_0*b_0  a_0*b_1 ... a_0*b_{N-1} ]

   [a_1*b_0    .

   [ ...          .
   
   [a_{M-1}*b_0            a_{M-1}*b_{N-1} ]]
   

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy --> "numpy.outer(a, b, out=None)" computes the outer product of two vectors "a" and ""b".
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [41]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
outer_np = np.outer(u,v)
outer_l = np.array([
    [u[0]*v[i] for i in range(len(u))], 
    [u[1]*v[i] for i in range(len(u))], 
    [u[2]*v[i] for i in range(len(u))], 
    [u[3]*v[i] for i in range(len(u))]
])
outer_np == outer_l

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
row1 = list(u[0]*v)
row2 = list(u[1]*v)
row3 = list(u[2]*v)
row4 = list(u[3]*v)
outer_b = np.array([row1, row2, row3, row4])
outer_np == outer_b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions:
- np.random.random --> The numpy.random module implements pseudo-random number generators with the ability to draw samples from a variety of probability distributions.
- np.any --> numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>) It tests whether any array element along a given axis evaluates to True.

Returns single boolean if axis is None
- as well as Boolean indexing and the axis argument.

In [161]:
import numpy.random as npr
npr.seed(123)

In [162]:
ra = np.array([list(npr.random(10)) for _ in range(6)])
print(len(ra), "\n", ra.shape, "\n\n", ra)

6 
 (6, 10) 

 [[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
  0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426 0.73799541
  0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338 0.32295891
  0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029 0.31226122
  0.42635131 0.89338916 0.94416002 0.50183668]
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916 0.25045537
  0.48303426 0.98555979 0.51948512 0.61289453]
 [0.12062867 0.8263408  0.60306013 0.54506801 0.34276383 0.30412079
  0.41702221 0.68130077 0.87545684 0.51042234]]


In [163]:
any_rr = ra.any(axis=1, keepdims=True, where=ra<0.1)
print(list(any_rr[:,0]))
list(any_rr[:,0])[0] is np.True_

[np.False_, np.True_, np.False_, np.True_, np.False_, np.False_]


False

In [169]:
for i, j in enumerate(list(any_rr[:,0])):
    print(f"Row_{i+1} with entry less than 1:", j, "\n")
    print(f"Row_{i+1} visualization:\n", ra[i], "\n")
    if j is np.True_: 
        ra[i] = 0
print("\nFiltered random matrix:\n", ra)

Row_1 with entry less than 1: False 

Row_1 visualization:
 [0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752] 

Row_2 with entry less than 1: True 

Row_2 visualization:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Row_3 with entry less than 1: False 

Row_3 visualization:
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338 0.32295891
 0.36178866 0.22826323 0.29371405 0.63097612] 

Row_4 with entry less than 1: True 

Row_4 visualization:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

Row_5 with entry less than 1: False 

Row_5 visualization:
 [0.62395295 0.1156184  0.31728548 0.41482621 0.86630916 0.25045537
 0.48303426 0.98555979 0.51948512 0.61289453] 

Row_6 with entry less than 1: False 

Row_6 visualization:
 [0.12062867 0.8263408  0.60306013 0.54506801 0.34276383 0.30412079
 0.41702221 0.68130077 0.87545684 0.51042234] 


Filtered random matrix:
 [[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
  0.9807642  0.68482

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.