# OSEMN Exercises

In [4]:
%matplotlib inline
import pandas as pd
import numpy as np
import csv

np.random.seed(123)

1\. Create a random list of numbers and then save it to a text file named "simple_data.txt"

In [2]:
rlist = [np.random.random() for _ in range(1000)]
print(rlist[:5], len(rlist))

[0.6964691855978616, 0.28613933495037946, 0.2268514535642031, 0.5513147690828912, 0.7194689697855631] 1000


In [3]:
with open('simple_data.txt', 'w') as f:
    for line in rlist:
        f.write(f"{line}\n")

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [4]:
rmatrix = np.random.random(size=(5,5))
rmatrix

array([[0.08189444, 0.49503963, 0.28889007, 0.63999187, 0.49993595],
       [0.03604485, 0.3186339 , 0.48905919, 0.57220384, 0.10487129],
       [0.64997129, 0.34369768, 0.18292129, 0.80532669, 0.06862339],
       [0.92976985, 0.70626616, 0.47559102, 0.01116088, 0.39012531],
       [0.64579841, 0.8589131 , 0.61776399, 0.39770742, 0.44735939]])

In [ ]:
with open('data.txt', 'w') as f:
    for line in rmatrix:
        f.write("".join(str(line)) + "\n")

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [7]:
data_text = open('data.txt', 'r')
print(data_text.read())

[0.08189444 0.49503963 0.28889007 0.63999187 0.49993595]
[0.03604485 0.3186339  0.48905919 0.57220384 0.10487129]
[0.64997129 0.34369768 0.18292129 0.80532669 0.06862339]
[0.92976985 0.70626616 0.47559102 0.01116088 0.39012531]
[0.64579841 0.8589131  0.61776399 0.39770742 0.44735939]



In [ ]:
with open('data.txt', 'r') as infile, open('data.csv', 'w') as outfile:
        stripped = (line.strip() for line in infile)
        replaced1 = (strip.replace("[", "") for strip in stripped)
        replaced2 = (strip.replace("]", "") for strip in replaced1)
        lines = (line.split(",") for line in replaced2 if line)
        writer = csv.writer(outfile)
        writer.writerows(lines)

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [11]:
credit_data = open('credit_card.dat', 'r')
file_content = credit_data.read()

with open('credit_card.dat', 'r') as data_file:
    for line in csv.reader(data_file, delimiter=','):
        print(line)

['1101111101101101001110001000001101011101101101111100111000001100111101111101111101011000001100101100101101111100011010']
['1100111100101101011101111000001110001100101101001101111000001100111100111101011101001000001100101100101101101101101010']
['1100101101111100101100101000001100001100001100001100011000001101001100001100011100011000001101101101101101011100101010']
['1100001101101101101100011000001100111100001101101100111000001100111101111101001100101000001100111100011101011100001010']
['1100001101001100111100101000001100011101101100001110001000001100011101001101101100101000001101001101111101001100101010']
['1101011110001100101101111000001100101100001100101101111000001110001101111110001101011000001101111100111100001100111010']
['1101011101111101111101001000001110001101011100101110001000001100101100001110001101111000001100011100011100011101111010']
['1110001100011101001100001000001100011100101100011100001000001101101100111101011100101000001100101110001101001101011010']
['11010111011111

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.